/* Formelsammlung: die Bereiche außerhalb der Analysis.
   Jeder Eintrag: { bereich, gruppe, name, f, kurz }.
   f ist Mini-TeX für <M>, siehe mLies in func3.jsx. */

export const FORMEL_BEREICHE = [
  { id: "analysis", name: "Analysis" },
  { id: "vektoren", name: "Vektoren" },
  { id: "stochastik", name: "Stochastik" },
  { id: "kopfrechnen", name: "Kopfrechnen" },
  { id: "trigonometrie", name: "Trigonometrie" },
  { id: "terme", name: "Terme und Gleichungen" },
  { id: "logik", name: "Mengenlehre und Logik" },
];

const b = (bereich, liste) => liste.map((e) => ({ bereich, ...e }));

export const FORMELN_ANALYSIS_EXTRA = b("analysis", [
  { gruppe: "Integralrechnung", name: "Stammfunktion", f: "F′(x) = f(x)",
    kurz: "jede Stammfunktion ist nur bis auf eine Konstante C bestimmt" },
  { gruppe: "Integralrechnung", name: "Potenzregel rückwärts", f: "\\int x^n \\, dx = \\frac{1}{n+1} x^{n+1} + C",
    kurz: "gilt für n ≠ −1 · für 1/x ist ln|x| die Stammfunktion" },
  { gruppe: "Integralrechnung", name: "Hauptsatz", f: "\\int_a^b f(x) \\, dx = F(b) - F(a)",
    kurz: "verbindet Fläche und Stammfunktion" },
  { gruppe: "Integralrechnung", name: "Fläche zwischen Graphen", f: "A = \\int_a^b |f(x) - g(x)| \\, dx",
    kurz: "Schnittstellen als Grenzen · zwischen ihnen einzeln integrieren" },
  { gruppe: "Integralrechnung", name: "Mittelwert", f: "\\overline{m} = \\frac{1}{b-a} \\int_a^b f(x) \\, dx",
    kurz: "durchschnittlicher Funktionswert auf [a ; b]" },
  { gruppe: "Integralrechnung", name: "Rotationsvolumen", f: "V = \\pi \\int_a^b (f(x))^2 \\, dx",
    kurz: "Rotation des Graphen um die x-Achse" },
]);

export const FORMELN_WEITERE = [
  ...b("vektoren", [
    { gruppe: "Grundlagen", name: "Verbindungsvektor", f: "\\vec{AB} = \\vec{b} - \\vec{a}",
      kurz: "Spitze minus Fuß · Ortsvektoren der Punkte" },
    { gruppe: "Grundlagen", name: "Betrag (Länge)", f: "|\\vec{a}| = \\sqrt{a_1^2 + a_2^2 + a_3^2}",
      kurz: "Abstand zweier Punkte: Betrag des Verbindungsvektors" },
    { gruppe: "Grundlagen", name: "Mittelpunkt", f: "\\vec{m} = \\frac{1}{2}(\\vec{a} + \\vec{b})",
      kurz: "Mittelwert der Koordinaten" },
    { gruppe: "Grundlagen", name: "Einheitsvektor", f: "\\vec{a}_0 = \\frac{1}{|\\vec{a}|} \\cdot \\vec{a}",
      kurz: "gleiche Richtung, Länge 1" },
    { gruppe: "Produkte", name: "Skalarprodukt", f: "\\vec{a} \\cdot \\vec{b} = a_1 b_1 + a_2 b_2 + a_3 b_3",
      kurz: "Ergebnis ist eine Zahl, kein Vektor" },
    { gruppe: "Produkte", name: "Orthogonalität", f: "\\vec{a} \\perp \\vec{b} \\quad\\Leftrightarrow\\quad \\vec{a} \\cdot \\vec{b} = 0",
      kurz: "senkrecht genau dann, wenn das Skalarprodukt null ist" },
    { gruppe: "Produkte", name: "Winkel zwischen Vektoren", f: "\\cos \\alpha = \\frac{\\vec{a} \\cdot \\vec{b}}{|\\vec{a}| \\cdot |\\vec{b}|}",
      kurz: "liefert Winkel zwischen 0° und 180°" },
    { gruppe: "Produkte", name: "Kreuzprodukt", f: "\\vec{a} \\times \\vec{b} = \\spalte{a_2 b_3 - a_3 b_2}{a_3 b_1 - a_1 b_3}{a_1 b_2 - a_2 b_1}",
      kurz: "steht senkrecht auf beiden Vektoren · nur im Raum" },
    { gruppe: "Geraden und Ebenen", name: "Geradengleichung", f: "g: \\vec{x} = \\vec{p} + t \\cdot \\vec{u}",
      kurz: "Stützvektor plus Vielfache des Richtungsvektors" },
    { gruppe: "Geraden und Ebenen", name: "Ebene in Parameterform", f: "E: \\vec{x} = \\vec{p} + r \\cdot \\vec{u} + s \\cdot \\vec{v}",
      kurz: "zwei Spannvektoren, die nicht parallel sind" },
    { gruppe: "Geraden und Ebenen", name: "Ebene in Normalenform", f: "E: (\\vec{x} - \\vec{p}) \\cdot \\vec{n} = 0",
      kurz: "Normalenvektor steht senkrecht auf der Ebene" },
    { gruppe: "Geraden und Ebenen", name: "Koordinatenform", f: "E: n_1 x_1 + n_2 x_2 + n_3 x_3 = d",
      kurz: "Koeffizienten sind die Koordinaten des Normalenvektors" },
    { gruppe: "Abstände und Winkel", name: "Abstand Punkt–Ebene", f: "d = \\frac{|n_1 q_1 + n_2 q_2 + n_3 q_3 - d|}{|\\vec{n}|}",
      kurz: "Hessesche Normalform · Punkt Q einsetzen" },
    { gruppe: "Abstände und Winkel", name: "Winkel Gerade–Ebene", f: "\\sin \\alpha = \\frac{|\\vec{u} \\cdot \\vec{n}|}{|\\vec{u}| \\cdot |\\vec{n}|}",
      kurz: "Sinus, weil der Normalenvektor senkrecht steht" },
    { gruppe: "Abstände und Winkel", name: "Winkel Ebene–Ebene", f: "\\cos \\alpha = \\frac{|\\vec{n}_1 \\cdot \\vec{n}_2|}{|\\vec{n}_1| \\cdot |\\vec{n}_2|}",
      kurz: "Winkel zwischen den Normalenvektoren" },
    { gruppe: "Abstände und Winkel", name: "Parallelogrammfläche", f: "A = |\\vec{a} \\times \\vec{b}|",
      kurz: "Dreieck: die Hälfte davon" },
    { gruppe: "Abstände und Winkel", name: "Spatvolumen", f: "V = |(\\vec{a} \\times \\vec{b}) \\cdot \\vec{c}|",
      kurz: "Pyramide mit dreieckiger Grundfläche: ein Sechstel" },
  ]),

  ...b("stochastik", [
    { gruppe: "Wahrscheinlichkeiten", name: "Laplace-Wahrscheinlichkeit", f: "P(A) = \\frac{|A|}{|\\Omega|}",
      kurz: "günstige durch mögliche Ergebnisse · nur bei gleich wahrscheinlichen Ergebnissen" },
    { gruppe: "Wahrscheinlichkeiten", name: "Gegenereignis", f: "P(\\overline{A}) = 1 - P(A)",
      kurz: "oft der schnellste Weg, besonders bei »mindestens«" },
    { gruppe: "Wahrscheinlichkeiten", name: "Additionssatz", f: "P(A \\cup B) = P(A) + P(B) - P(A \\cap B)",
      kurz: "die Schnittmenge wird sonst doppelt gezählt" },
    { gruppe: "Wahrscheinlichkeiten", name: "Mindestens einmal", f: "P(X \\geq 1) = 1 - (1-p)^n",
      kurz: "über das Gegenereignis »kein einziges Mal«" },
    { gruppe: "Bedingte Wahrscheinlichkeit", name: "Bedingte Wahrscheinlichkeit", f: "P_B(A) = \\frac{P(A \\cap B)}{P(B)}",
      kurz: "Wahrscheinlichkeit von A, wenn B schon eingetreten ist" },
    { gruppe: "Bedingte Wahrscheinlichkeit", name: "Unabhängigkeit", f: "P(A \\cap B) = P(A) \\cdot P(B)",
      kurz: "gleichwertig: P_B(A) = P(A)" },
    { gruppe: "Bedingte Wahrscheinlichkeit", name: "Satz von Bayes", f: "P_B(A) = \\frac{P(A) \\cdot P_A(B)}{P(B)}",
      kurz: "dreht die Bedingung um · Baumdiagramm rückwärts lesen" },
    { gruppe: "Kombinatorik", name: "Fakultät", f: "n! = 1 \\cdot 2 \\cdot 3 \\cdot \\ldots \\cdot n",
      kurz: "Anzahl der Anordnungen von n Objekten · 0! = 1" },
    { gruppe: "Kombinatorik", name: "Binomialkoeffizient", f: "\\binom{n}{k} = \\frac{n!}{k! \\cdot (n-k)!}",
      kurz: "k aus n ziehen, ohne Reihenfolge, ohne Zurücklegen" },
    { gruppe: "Kombinatorik", name: "Mit Reihenfolge, mit Zurücklegen", f: "n^k",
      kurz: "z. B. Zahlenschloss mit k Stellen" },
    { gruppe: "Zufallsgrößen", name: "Erwartungswert", f: "E(X) = \\mu = x_1 p_1 + x_2 p_2 + \\ldots + x_n p_n",
      kurz: "langfristiger Mittelwert · Spiel fair, wenn E = 0" },
    { gruppe: "Zufallsgrößen", name: "Varianz", f: "V(X) = (x_1 - \\mu)^2 p_1 + \\ldots + (x_n - \\mu)^2 p_n",
      kurz: "mittlere quadratische Abweichung vom Erwartungswert" },
    { gruppe: "Zufallsgrößen", name: "Standardabweichung", f: "\\sigma = \\sqrt{V(X)}",
      kurz: "gleiche Einheit wie X" },
    { gruppe: "Binomialverteilung", name: "Bernoulli-Formel", f: "P(X = k) = \\binom{n}{k} \\cdot p^k \\cdot (1-p)^{n-k}",
      kurz: "genau k Treffer bei n unabhängigen Versuchen" },
    { gruppe: "Binomialverteilung", name: "Erwartungswert und Varianz", f: "\\mu = n \\cdot p, \\quad \\sigma^2 = n \\cdot p \\cdot (1-p)",
      kurz: "nur für binomialverteilte Zufallsgrößen" },
    { gruppe: "Binomialverteilung", name: "Höchstens und mindestens", f: "P(X \\geq k) = 1 - P(X \\leq k-1)",
      kurz: "kumulierte Tabelle oder Taschenrechner nutzen" },
  ]),

  ...b("kopfrechnen", [
    { gruppe: "Rechengesetze", name: "Kommutativgesetz", f: "a + b = b + a, \\quad a \\cdot b = b \\cdot a",
      kurz: "Reihenfolge so wählen, dass es leichter wird" },
    { gruppe: "Rechengesetze", name: "Assoziativgesetz", f: "(a + b) + c = a + (b + c)",
      kurz: "z. B. 37 + 48 + 52 = 37 + 100" },
    { gruppe: "Rechengesetze", name: "Distributivgesetz", f: "a \\cdot (b + c) = a \\cdot b + a \\cdot c",
      kurz: "z. B. 7 · 49 = 7 · 50 − 7 = 343" },
    { gruppe: "Rechentricks", name: "Mal 11", f: "43 \\cdot 11 = 4 \\, (4+3) \\, 3 = 473",
      kurz: "Ziffernsumme in die Mitte · bei Übertrag vorne +1" },
    { gruppe: "Rechentricks", name: "Mal 5", f: "a \\cdot 5 = \\frac{a \\cdot 10}{2}",
      kurz: "z. B. 68 · 5 = 680 : 2 = 340" },
    { gruppe: "Rechentricks", name: "Mal 25", f: "a \\cdot 25 = \\frac{a \\cdot 100}{4}",
      kurz: "z. B. 36 · 25 = 3600 : 4 = 900" },
    { gruppe: "Rechentricks", name: "Quadrat mit Endziffer 5", f: "(10a + 5)^2 = a(a+1) \\cdot 100 + 25",
      kurz: "z. B. 65² : 6 · 7 = 42, dahinter 25 → 4225" },
    { gruppe: "Rechentricks", name: "Um die Mitte herum", f: "49 \\cdot 51 = 50^2 - 1^2 = 2499",
      kurz: "dritte binomische Formel im Kopf" },
    { gruppe: "Rechentricks", name: "Nahe an 100", f: "98 \\cdot 97 = (98 - 3) \\cdot 100 + 2 \\cdot 3 = 9506",
      kurz: "Abstände zu 100 multiplizieren und anhängen" },
    { gruppe: "Teilbarkeit", name: "Durch 2, 5, 10", f: "\\text{Endziffer prüfen}",
      kurz: "2: gerade · 5: 0 oder 5 · 10: 0" },
    { gruppe: "Teilbarkeit", name: "Durch 3 und 9", f: "\\text{Quersumme durch 3 bzw. 9 teilbar}",
      kurz: "z. B. 4572: Quersumme 18 → durch 3 und 9 teilbar" },
    { gruppe: "Teilbarkeit", name: "Durch 4 und 8", f: "\\text{letzte 2 bzw. 3 Ziffern}",
      kurz: "z. B. 7316: 16 ist durch 4 teilbar" },
    { gruppe: "Teilbarkeit", name: "Durch 6", f: "\\text{durch 2 und durch 3}",
      kurz: "beide Regeln müssen gelten" },
    { gruppe: "Bruchrechnen", name: "Addieren", f: "\\frac{a}{b} + \\frac{c}{d} = \\frac{ad + bc}{bd}",
      kurz: "erst auf einen gemeinsamen Nenner bringen" },
    { gruppe: "Bruchrechnen", name: "Multiplizieren", f: "\\frac{a}{b} \\cdot \\frac{c}{d} = \\frac{a \\cdot c}{b \\cdot d}",
      kurz: "vorher kürzen spart Arbeit" },
    { gruppe: "Bruchrechnen", name: "Dividieren", f: "\\frac{a}{b} : \\frac{c}{d} = \\frac{a}{b} \\cdot \\frac{d}{c}",
      kurz: "mit dem Kehrwert multiplizieren" },
    { gruppe: "Bruchrechnen", name: "Prozent", f: "W = G \\cdot \\frac{p}{100}",
      kurz: "Prozentwert = Grundwert mal Prozentsatz" },
  ]),

  ...b("trigonometrie", [
    { gruppe: "Rechtwinkliges Dreieck", name: "Satz des Pythagoras", f: "a^2 + b^2 = c^2",
      kurz: "c ist die Hypotenuse, gegenüber dem rechten Winkel" },
    { gruppe: "Rechtwinkliges Dreieck", name: "Sinus", f: "\\sin \\alpha = \\frac{\\text{Gegenkathete}}{\\text{Hypotenuse}}",
      kurz: "Kathete gegenüber von α" },
    { gruppe: "Rechtwinkliges Dreieck", name: "Kosinus", f: "\\cos \\alpha = \\frac{\\text{Ankathete}}{\\text{Hypotenuse}}",
      kurz: "Kathete, die an α anliegt" },
    { gruppe: "Rechtwinkliges Dreieck", name: "Tangens", f: "\\tan \\alpha = \\frac{\\text{Gegenkathete}}{\\text{Ankathete}} = \\frac{\\sin \\alpha}{\\cos \\alpha}",
      kurz: "entspricht der Steigung einer Geraden" },
    { gruppe: "Allgemeines Dreieck", name: "Winkelsumme", f: "\\alpha + \\beta + \\gamma = 180°",
      kurz: "in jedem ebenen Dreieck" },
    { gruppe: "Allgemeines Dreieck", name: "Sinussatz", f: "\\frac{a}{\\sin \\alpha} = \\frac{b}{\\sin \\beta} = \\frac{c}{\\sin \\gamma}",
      kurz: "wenn eine Seite und ihr Gegenwinkel bekannt sind" },
    { gruppe: "Allgemeines Dreieck", name: "Kosinussatz", f: "c^2 = a^2 + b^2 - 2ab \\cdot \\cos \\gamma",
      kurz: "verallgemeinerter Pythagoras · für γ = 90° wieder Pythagoras" },
    { gruppe: "Allgemeines Dreieck", name: "Flächeninhalt", f: "A = \\frac{1}{2} \\, a b \\cdot \\sin \\gamma",
      kurz: "zwei Seiten und der eingeschlossene Winkel" },
    { gruppe: "Zusammenhänge", name: "Trigonometrischer Pythagoras", f: "\\sin^2 \\alpha + \\cos^2 \\alpha = 1",
      kurz: "folgt direkt aus dem Einheitskreis" },
    { gruppe: "Zusammenhänge", name: "Bogenmaß", f: "x = \\frac{\\alpha}{180°} \\cdot \\pi",
      kurz: "180° entsprechen π · in der Analysis immer Bogenmaß" },
    { gruppe: "Zusammenhänge", name: "Symmetrien", f: "\\sin(-x) = -\\sin x, \\quad \\cos(-x) = \\cos x",
      kurz: "Sinus punktsymmetrisch, Kosinus achsensymmetrisch" },
    { gruppe: "Zusammenhänge", name: "Verschiebung", f: "\\sin\\left(x + \\frac{\\pi}{2}\\right) = \\cos x",
      kurz: "Kosinus ist der um π/2 verschobene Sinus" },
    { gruppe: "Zusammenhänge", name: "Periode", f: "\\sin(x + 2\\pi) = \\sin x",
      kurz: "f(x) = sin(bx) hat die Periode 2π/b" },
    { gruppe: "Standardwerte", name: "Sinuswerte", f: "\\sin 0° = 0, \\; \\sin 30° = \\frac{1}{2}, \\; \\sin 45° = \\frac{\\sqrt{2}}{2}, \\; \\sin 60° = \\frac{\\sqrt{3}}{2}, \\; \\sin 90° = 1",
      kurz: "Merkhilfe: √0/2, √1/2, √2/2, √3/2, √4/2" },
    { gruppe: "Standardwerte", name: "Kosinuswerte", f: "\\cos 0° = 1, \\; \\cos 60° = \\frac{1}{2}, \\; \\cos 90° = 0",
      kurz: "dieselben Werte wie beim Sinus, nur rückwärts" },
  ]),

  ...b("terme", [
    { gruppe: "Binomische Formeln", name: "Erste binomische Formel", f: "(a + b)^2 = a^2 + 2ab + b^2",
      kurz: "das gemischte Glied 2ab nie vergessen" },
    { gruppe: "Binomische Formeln", name: "Zweite binomische Formel", f: "(a - b)^2 = a^2 - 2ab + b^2",
      kurz: "Minus nur beim gemischten Glied" },
    { gruppe: "Binomische Formeln", name: "Dritte binomische Formel", f: "(a + b)(a - b) = a^2 - b^2",
      kurz: "rückwärts gelesen: Faktorisieren einer Differenz" },
    { gruppe: "Potenzen und Wurzeln", name: "Potenzgesetze", f: "a^m \\cdot a^n = a^{m+n}, \\quad \\frac{a^m}{a^n} = a^{m-n}",
      kurz: "gleiche Basis: Exponenten addieren bzw. subtrahieren" },
    { gruppe: "Potenzen und Wurzeln", name: "Potenz einer Potenz", f: "(a^m)^n = a^{m \\cdot n}, \\quad a^n \\cdot b^n = (ab)^n",
      kurz: "gleicher Exponent: Basen multiplizieren" },
    { gruppe: "Potenzen und Wurzeln", name: "Negative Exponenten", f: "a^{-n} = \\frac{1}{a^n}, \\quad a^0 = 1",
      kurz: "gilt für a ≠ 0" },
    { gruppe: "Potenzen und Wurzeln", name: "Wurzel als Potenz", f: "\\sqrt[n]{a^m} = a^{\\frac{m}{n}}",
      kurz: "Wurzelgesetze sind Potenzgesetze" },
    { gruppe: "Logarithmen", name: "Definition", f: "a^x = b \\quad\\Leftrightarrow\\quad x = \\log_a b",
      kurz: "Logarithmus ist der gesuchte Exponent" },
    { gruppe: "Logarithmen", name: "Logarithmengesetze", f: "\\log(u \\cdot v) = \\log u + \\log v, \\quad \\log \\frac{u}{v} = \\log u - \\log v",
      kurz: "aus Produkten werden Summen" },
    { gruppe: "Logarithmen", name: "Potenz im Logarithmus", f: "\\log(u^r) = r \\cdot \\log u",
      kurz: "der wichtigste Schritt beim Lösen von Exponentialgleichungen" },
    { gruppe: "Gleichungen", name: "Lineare Gleichung", f: "ax + b = 0 \\quad\\Rightarrow\\quad x = -\\frac{b}{a}",
      kurz: "Äquivalenzumformungen auf beiden Seiten" },
    { gruppe: "Gleichungen", name: "Mitternachtsformel", f: "x_{1,2} = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}",
      kurz: "für ax² + bx + c = 0 · Diskriminante entscheidet über die Anzahl" },
    { gruppe: "Gleichungen", name: "pq-Formel", f: "x_{1,2} = -\\frac{p}{2} \\pm \\sqrt{\\left(\\frac{p}{2}\\right)^2 - q}",
      kurz: "für x² + px + q = 0 · vorher durch a teilen" },
    { gruppe: "Gleichungen", name: "Satz von Vieta", f: "x_1 + x_2 = -p, \\quad x_1 \\cdot x_2 = q",
      kurz: "schnelle Probe für die pq-Formel" },
    { gruppe: "Gleichungen", name: "Satz vom Nullprodukt", f: "a \\cdot b = 0 \\quad\\Leftrightarrow\\quad a = 0 \\; \\lor \\; b = 0",
      kurz: "erst ausklammern, dann jeden Faktor null setzen" },
    { gruppe: "Gleichungen", name: "Exponentialgleichung", f: "a^x = b \\quad\\Rightarrow\\quad x = \\frac{\\ln b}{\\ln a}",
      kurz: "beide Seiten logarithmieren" },
    { gruppe: "Lineare Funktionen", name: "Geradengleichung", f: "f(x) = mx + b",
      kurz: "m ist die Steigung, b der y-Achsenabschnitt" },
    { gruppe: "Lineare Funktionen", name: "Steigung", f: "m = \\frac{y_2 - y_1}{x_2 - x_1}",
      kurz: "Steigungsdreieck zwischen zwei Punkten" },
  ]),

  ...b("logik", [
    { gruppe: "Mengen", name: "Element", f: "x \\in A, \\quad y \\notin A",
      kurz: "x gehört zur Menge A, y nicht" },
    { gruppe: "Mengen", name: "Teilmenge", f: "A \\subseteq B \\quad\\Leftrightarrow\\quad (x \\in A \\Rightarrow x \\in B)",
      kurz: "jedes Element von A liegt auch in B" },
    { gruppe: "Mengen", name: "Vereinigung", f: "A \\cup B = \\{ x \\mid x \\in A \\lor x \\in B \\}",
      kurz: "alles, was in A oder in B liegt" },
    { gruppe: "Mengen", name: "Schnittmenge", f: "A \\cap B = \\{ x \\mid x \\in A \\land x \\in B \\}",
      kurz: "nur, was in beiden liegt" },
    { gruppe: "Mengen", name: "Differenzmenge", f: "A \\setminus B = \\{ x \\mid x \\in A \\land x \\notin B \\}",
      kurz: "A ohne die Elemente von B" },
    { gruppe: "Mengen", name: "Leere Menge", f: "\\emptyset = \\{ \\}",
      kurz: "Teilmenge jeder Menge" },
    { gruppe: "Mengen", name: "Zahlbereiche", f: "\\mathbb{N} \\subset \\mathbb{Z} \\subset \\mathbb{Q} \\subset \\mathbb{R} \\subset \\mathbb{C}",
      kurz: "natürliche, ganze, rationale, reelle, komplexe Zahlen" },
    { gruppe: "Mengen", name: "Intervalle", f: "[a ; b] = \\{ x \\in \\mathbb{R} \\mid a \\leq x \\leq b \\}",
      kurz: "eckige Klammer nach außen: Grenze gehört nicht dazu" },
    { gruppe: "Mengen", name: "De Morgan (Mengen)", f: "\\overline{A \\cup B} = \\overline{A} \\cap \\overline{B}",
      kurz: "Komplement dreht ∪ und ∩ um" },
    { gruppe: "Aussagenlogik", name: "Und, Oder, Nicht", f: "A \\land B, \\quad A \\lor B, \\quad \\neg A",
      kurz: "»oder« ist immer einschließend gemeint" },
    { gruppe: "Aussagenlogik", name: "Implikation", f: "A \\Rightarrow B",
      kurz: "nur falsch, wenn A wahr und B falsch ist" },
    { gruppe: "Aussagenlogik", name: "Äquivalenz", f: "A \\Leftrightarrow B \\quad\\Leftrightarrow\\quad (A \\Rightarrow B) \\land (B \\Rightarrow A)",
      kurz: "»genau dann, wenn« · beide Richtungen zeigen" },
    { gruppe: "Aussagenlogik", name: "Kontraposition", f: "(A \\Rightarrow B) \\quad\\Leftrightarrow\\quad (\\neg B \\Rightarrow \\neg A)",
      kurz: "Vorsicht: B ⇒ A folgt daraus nicht" },
    { gruppe: "Aussagenlogik", name: "De Morgan (Logik)", f: "\\neg(A \\land B) \\quad\\Leftrightarrow\\quad \\neg A \\lor \\neg B",
      kurz: "Verneinung dreht ∧ und ∨ um" },
    { gruppe: "Aussagenlogik", name: "Quantoren", f: "\\forall x : A(x), \\quad \\exists x : A(x)",
      kurz: "»für alle« und »es gibt« · Verneinung tauscht die beiden" },
    { gruppe: "Beweisverfahren", name: "Direkter Beweis", f: "A \\Rightarrow C_1 \\Rightarrow C_2 \\Rightarrow B",
      kurz: "Kette gültiger Schlüsse von der Voraussetzung zur Behauptung" },
    { gruppe: "Beweisverfahren", name: "Widerspruchsbeweis", f: "\\neg B \\Rightarrow \\text{Widerspruch}",
      kurz: "z. B. √2 ist irrational" },
    { gruppe: "Beweisverfahren", name: "Vollständige Induktion", f: "A(1) \\land (A(n) \\Rightarrow A(n+1))",
      kurz: "Induktionsanfang und Induktionsschritt · dann gilt A(n) für alle n" },
  ]),
];
